[Feat]: Autoplay:triggered event
davidjerleke/embla-carousel pull request #1054
Opened 2024-11-06 18:05 UTC by Mitch-At-Work

Emit autoplay:triggered event on autoplay index change as discussed in:
 https://github.com/davidjerleke/embla-carousel/discussions/1048

Event is emitted after index change; listeners can retrieve the latest selectedScrollSnap from emblaApi regardless of direction to be compatible with upcoming autoplay direction feature.

2024-11-07 08:55 UTC, davidjerleke requested changes
Nicely done.

Just two minor comments. Additionally, we should add the event [here](https://www.embla-carousel.com/plugins/autoplay/#events) in the docs.

2024-11-07 08:55 UTC, davidjerleke commented on packages/embla-carousel-autoplay/src/components/Autoplay.ts
> +    autoplayTriggered: 'autoplay:triggered'
What do you think about renaming this to `autolplay:select`? That would be consistent with the core API but is a clear distinction that it's triggered by `Autoplay`.

2024-11-07 08:55 UTC, davidjerleke commented on packages/embla-carousel-autoplay/src/components/Autoplay.ts
> +    emblaApi.emit('autoplay:triggered')
Nitpick: Maybe add a space above this line?

2024-11-07 17:53 UTC, Mitch-At-Work commented on packages/embla-carousel-autoplay/src/components/Autoplay.ts
> +    autoplayTriggered: 'autoplay:triggered'
Sounds good! I'll make these updates today

2024-11-07 19:00 UTC, Mitch-At-Work commented on packages/embla-carousel-autoplay/src/components/Autoplay.ts
> +    autoplayTriggered: 'autoplay:select'
Todo: Fix up type name.

2024-11-07 19:06 UTC, davidjerleke approved these changes

2024-11-07 19:08 UTC, davidjerleke commented
Thanks for your contribution @Mitch-At-Work. Feel free to squash the commits into to a single commit with the message:

`Implement #1048.`

If not, I will do it when possible.

Cheers 👍🏻!

2024-11-08 17:15 UTC, merged

2024-11-08 17:16 UTC, davidjerleke commented
@Mitch-At-Work great work and thanks for your contribution. This feature will be included in the next release 🥳.