Feat: For Vue docs, use a more common SFC format
davidjerleke/embla-carousel pull request #701
Opened 2024-01-17 04:44 UTC by mujahidfa

To resolve https://github.com/davidjerleke/embla-carousel/discussions/700.

### Feature description

To use a format for Vue Single File Components (SFCs) that is more succint and commonly used by the Vue community.

As per what is shown in the [Introduction page of the Vue docs](https://vuejs.org/guide/introduction.html):
1. `<script setup>` is more commonly used, and 
2. `<script setup>` -> `<template>` -> `<style scoped>` order is more common

Here's the current example found in the docs:
```vue
<template>
  <div class="embla" ref="emblaNode">
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</template>

<script>
  import emblaCarouselVue from 'embla-carousel-vue'

  export default {
    setup() {
      const [emblaNode] = emblaCarouselVue()
      return { emblaNode }
    }
  }
</script>
```

And here's the _proposed change_ in format - less verbose, more commonly used:
```vue
<script setup>
import emblaCarouselVue from 'embla-carousel-vue'

const [emblaNode] = emblaCarouselVue()
</script>

<template>
  <div class="embla" ref="emblaNode">
    <div class="embla__container">
      <div class="embla__slide">Slide 1</div>
      <div class="embla__slide">Slide 2</div>
      <div class="embla__slide">Slide 3</div>
    </div>
  </div>
</template>
```

2024-01-18 08:15 UTC, davidjerleke requested changes
Hi @mujahidfa,

Thanks a lot for your contribution, great initiative 👍. While at it, would you mind going through the code blocks in the API section and see if we can find more places where we could use the more succinct syntax? For example:

- [https://www.embla-carousel.com/api/options/](https://www.embla-carousel.com/api/options/)
- [https://www.embla-carousel.com/api/methods/](https://www.embla-carousel.com/api/methods/)
- [https://www.embla-carousel.com/api/events/](https://www.embla-carousel.com/api/events/)
- [https://www.embla-carousel.com/api/plugins/](https://www.embla-carousel.com/api/plugins/)

Thanks a lot for your time!

Best,
David

2024-01-18 08:15 UTC, davidjerleke commented on packages/embla-carousel-docs/src/content/pages/get-started/vue.mdx
> +```vue
@mujahidfa did you start the documentation website locally to see if setting the code block to `vue` does show correct syntax highlighting?

2024-01-18 08:15 UTC, davidjerleke commented on packages/embla-carousel-docs/src/content/pages/get-started/vue.mdx
> +</script>
Nice work 👍!

2024-01-19 01:20 UTC, mujahidfa commented on packages/embla-carousel-docs/src/content/pages/get-started/vue.mdx
> +```vue
It didn't, but I added support to this in https://github.com/davidjerleke/embla-carousel/pull/701/commits/12f96e99070fbe7c09c3e11b9f748c48b99799b6 and now it does (via aliasing with HTML syntax):

<img width="451" alt="image" src="https://github.com/davidjerleke/embla-carousel/assets/17759705/5507e730-4026-44e1-845e-064a8a9c8bd7">

Now it has the `VUE` labelling at the code block instead of `HTML` which is nice 👍🏾

2024-01-19 02:05 UTC, mujahidfa commented
> Hi @mujahidfa,
> 
> Thanks a lot for your contribution, great initiative 👍. While at it, would you mind going through the code blocks in the API section and see if we can find more places where we could use the more succinct syntax? For example (`.mdx` files are located [here](https://github.com/davidjerleke/embla-carousel/tree/master/packages/embla-carousel-docs/src/content/pages/api)):
> 
> * https://www.embla-carousel.com/api/options/
> * https://www.embla-carousel.com/api/methods/
> * https://www.embla-carousel.com/api/events/
> * https://www.embla-carousel.com/api/plugins/
> 
> Thanks a lot for your time!
> 
> Best, David

Implemented in https://github.com/davidjerleke/embla-carousel/pull/701/commits/aea826e274d94c53be20aec490d1b84509876530!

2024-01-19 05:24 UTC, davidjerleke commented
@mujahidfa thanks for the additions 🙂!

2024-01-21 09:49 UTC, davidjerleke approved these changes
Nice work ⭐️! I will merge this as soon as possible.

2024-01-25 14:21 UTC, davidjerleke commented
Thanks @mujahidfa for this. Really nice improvement ⭐. I decided to scrap the `vue` prism language alias because it breaks syntax highlighting in the `.mdx` files which I think is pretty important. Other than that this is awesome.

Best,
David

2024-01-25 14:22 UTC, merged