feat: add RTL case for slide gaps via CSS
davidjerleke/embla-carousel pull request #786
Opened 2024-03-05 20:05 UTC by zaaakher

Hi @davidjerleke,

Hope you're doing well. 

This PR is a simple addition to the [slide-gaps](https://www.embla-carousel.com/guides/slide-gaps/) section of the docs to mention the RTL case.

Let me know If I missed something 

Best,
Zakher

2024-03-06 02:40 UTC, zaaakher commented
Note: formatting that file via prettier kept adding an extra backtick as seen on line 50

2024-03-06 11:20 UTC, davidjerleke commented
@zaaakher nice to have you back 🙂. Thanks for the contribution. I will review as soon as I get a chance.

Best,
David

2024-03-07 05:21 UTC, davidjerleke requested changes
Thanks as always for making this library better and easier to use 👍🏻.

Please see my minor comment and after fixing that I’m ready to merge this.

2024-03-07 05:21 UTC, davidjerleke commented on packages/embla-carousel-docs/src/content/pages/guides/slide-gaps.md
> +````css
> Note: formatting that file via prettier kept adding an extra backtick as seen on line 50

@zaaakher could this be the cause of `Prettier` going crazy? It seems like we can remove this line because it doesn’t have a closing ``` and it has 4 instead of three back ticks `.

2024-03-08 10:43 UTC, zaaakher commented on packages/embla-carousel-docs/src/content/pages/guides/slide-gaps.md
> +````css
@davidjerleke Yup, you're right. That extra opening was the culprit. I removed it in the latest commit. Let me know if I missed something else.

2024-03-08 11:50 UTC, davidjerleke commented on packages/embla-carousel-docs/src/content/pages/guides/slide-gaps.md
> +  margin-inline-start: 10px; //Space before the slide
@zaaakher sorry I missed this before, but the `//` isn't valid commenting for the CSS language, so it will not be treated as comments by the code highlighter (Prism). Let's make it this instead:

```suggestion
  margin-inline-end: 20px; /* Space after the slide */
  margin-inline-start: 10px; /* Space before the slide */
```

2024-03-09 15:39 UTC, zaaakher commented on packages/embla-carousel-docs/src/content/pages/guides/slide-gaps.md
> +  margin-inline-start: 10px; //Space before the slide
Fixed 👍

2024-03-09 15:42 UTC, zaaakher commented
I made the changes of this PR "blindfolded" (without running the docs gatsby app due to https://github.com/davidjerleke/embla-carousel/issues/662). So my apologies for missing tiny things here or there 😅

2024-03-09 16:38 UTC, davidjerleke commented
> I made the changes of this PR "blindfolded" (without running the docs gatsby app due to #662). So my apologies for missing tiny things here or there 😅

@zaaakher no worries. I’m thankful that you continuously want to make this library better! Thanks for the fixes. I’m ready to merge this now 🎉.

2024-03-09 16:38 UTC, davidjerleke approved these changes
Nice work ✨!

2024-03-09 21:59 UTC, zaaakher commented
> @zaaakher no worries. I’m thankful that you continuously want to make this library better! Thanks for the fixes. I’m ready to merge this as soon as I’ve squashed the commits 🎉.

You're welcome brother, it's my absolute pleasure. 🌹

2024-04-03 10:51 UTC, merged

2024-04-03 19:21 UTC, davidjerleke commented
Released in [v8.0.1](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.1).