Add robust pinch zoom support
davidjerleke/embla-carousel pull request #830
Opened 2024-04-19 15:22 UTC by realwagyu

https://github.com/davidjerleke/embla-carousel/discussions/828

2024-04-22 07:33 UTC, davidjerleke commented
@realwagyu thank you for your contribution 👍. I will review this when possible. Thanks for your patience.

Best,
David

2024-04-27 11:05 UTC, davidjerleke requested changes
Great initiative 👍!

I have one change request and would very much appreciate if you could test it on an Android device.

Thanks in advance!

2024-04-27 11:05 UTC, davidjerleke commented on packages/embla-carousel/src/components/DragHandler.ts
> +    }
Maybe we should release any ongoing scroll when there are multiple touches? Additionally there's already a utility function for checking if the `event` is a `TouchEvent` or a `MouseEvent`. It makes use of the `ownerWindow` instead of `window` which supports carousels from other realms like iframes.

So we could change your suggestion to this:

```suggestion
    const isTouchEvt = !isMouseEvent(evt, ownerWindow)
    if (isTouchEvt && evt.touches.length >= 2) return up(evt)
```

<br/>

I've tested on Safari and it behaves like this:


- Pinch zoom works in both directions (both the scroll direction and the opposite).
- A pinch move doesn't scroll the carousel (it terminates any ongoing `touchmove` listeners).
- If only one finger is touching the screen initially and it scrolls the carousel, and you add an additional finger (2 total), the carousel stops scrolling, but you have to release your fingers and perform a new pinch move to zoom.

2024-04-27 11:41 UTC, realwagyu commented on packages/embla-carousel/src/components/DragHandler.ts
> +    }
Yes, great!
With the modified commit, it works correctly/as you describe on:
- Android Chromium 116
- Android Firefox 124
- Android Opera Mini 79

2024-04-27 11:43 UTC, davidjerleke commented on packages/embla-carousel/src/components/DragHandler.ts
> +    }
@realwagyu thanks for testing! Feel free to push the modification and the additional change suggested [here](https://github.com/davidjerleke/embla-carousel/pull/830#pullrequestreview-2026630952) (see point 2) when you want. 

Thanks!

2024-04-27 12:09 UTC, realwagyu commented on packages/embla-carousel/src/components/DragHandler.ts
> +    }
Amended with both changes: https://github.com/davidjerleke/embla-carousel/pull/830/commits/6f5a6c96b27893ffe2a2186f100a3641e3054139

2024-04-27 13:05 UTC, davidjerleke commented on packages/embla-carousel/src/components/DragHandler.ts
> +    }
@realwagyu thanks a ton. I will merge this soon 🎉.

2024-04-27 13:05 UTC, davidjerleke approved these changes

2024-04-27 13:11 UTC, realwagyu commented on packages/embla-carousel/src/components/DragHandler.ts
> +    }
Thank you for this beautiful library

2024-04-28 09:36 UTC, davidjerleke commented on packages/embla-carousel/src/components/DragHandler.ts
> +    }
@realwagyu thanks! Would you mind rebasing your [commit](https://github.com/davidjerleke/embla-carousel/pull/830/commits/8d5eb22c00d95a98fbd0a7d774d075460c4f06b8) on the latest `davidjerleke/embla-carousel:master` and I will merge this afterwards?

2024-04-28 13:07 UTC, realwagyu commented on packages/embla-carousel/src/components/DragHandler.ts
> +    }
@davidjerleke done, let me know if you need anything else

2024-04-29 07:58 UTC, merged