fix(react): export EmblaViewportRefType from bundle
davidjerleke/embla-carousel pull request #947
Opened 2024-07-20 21:15 UTC by junlarsen

Hi David, thanks for your awesome work on Embla!

I recently wrote a small wrapper component around the react plugin and found it would be beneficial to pass around the Embla viewport ref type (for example uses like forwardRef).

This small patch re-exports EmblaViewportRefType from embla-carousel-react. Let me know if there are any questions!

2024-07-21 07:26 UTC, davidjerleke requested changes
Hi @junlarsen,

Thanks for your contribution! I think these changes make sense. We also need to export it from the `index` file:

https://github.com/davidjerleke/embla-carousel/blob/9d1cc8a235cbbcac783e270d44181d83076ed938/packages/embla-carousel-react/src/index.ts#L1

The reason why is because package managers like `pnpm` have introduced new behavior to the frontend world. For example, `pnpm` doesn’t allow imports from any other file than the `index` file, so any imports with paths to specific files will fail.

2024-07-21 15:17 UTC, junlarsen commented
Right, missed that one. I'll get on it tonight :)

2024-07-21 20:55 UTC, davidjerleke approved these changes

2024-07-22 05:01 UTC, davidjerleke commented
@junlarsen this is approved. Nicely done 👍🏻. Feel free to squash the commits into a single commit. Otherwise I will do it before merging this PR.

2024-07-23 06:51 UTC, merged

2024-07-23 06:52 UTC, davidjerleke commented
Thanks @junlarsen 👍🏻!

2024-07-31 19:48 UTC, davidjerleke commented
@junlarsen your fix has been included in [`v8.1.8`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.8) which I just released.

2024-07-31 23:50 UTC, junlarsen commented
Great, thank you!